name: Periodic Sync

on:
  schedule:
    - cron: '0 0 * * *' # RUN AT 12:00 AM EVERYDAY
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: sync the forked repo
        run: |
          git remote add upstream https://github.com/torvalds/linux.git
          git fetch upstream master
          git merge upstream/master
          git fetch --tags upstream master
          git merge --tags upstream/master --force
        shell: bash
